## this script is only needed if the db/map_countx.sqlite db gets deleted
## that db is intended to be used to check that the number of rows per table
## doesn't vary by too much as compared to the last time we built the annotations.

## If db/map_counts.sqlite doesn't exist, we need to get the row counts from the
## existing db0, KEGG, PFAM and GO packages. The database will be generated by
## updateMapCounts.R, so this script has to go first

## checking for existence of the map_counts.sqlite occurs in updateMapCounts.R

pkgnames <- c("GO.db","KEGG.db","PFAM.db","anopheles.db0", "arabidopsis.db0", "bovine.db0",
              "canine.db0", "chicken.db0", "chimp.db0", "ecoliK12.db0", "ecoliSakai.db0",
              "fly.db0", "human.db0", "malaria.db0", "mouse.db0", "pig.db0", "rat.db0",
              "rhesus.db0", "worm.db0", "xenopus.db0", "yeast.db0", "zebrafish.db0")

.libPaths("~/R-libraries")
library(DBI)
library("RSQLite")

tablenames <- c("GO", "KEGG", "PFAM", "chipsrc_anopheles", "chipsrc_arabidopsis", "chipsrc_bovine",
                       "chipsrc_canine", "chipsrc_chicken", "chipsrc_chimp", "chipsrc_ecoliK12",
                       "chipsrc_ecoliSakai", "chipsrc_fly", "chipsrc_human", "chipsrc_malaria",
                       "chipsrc_mouse", "chipsrc_pig", "chipsrc_rat", "chipsrc_rhesus", "chipsrc_worm",
                       "chipsrc_xenopus", "chipsrc_yeast", "chipsrc_zebrafish")

installed <- pkgnames %in% row.names(installed.packages())

if(any(!installed)) {
    require("BiocManager", quietly = TRUE, character.only = TRUE)
    BiocManager::install(pkgnames[!installed], ask = FALSE)
}

## get fake last date

library(GO.db)

fdate <- dbGetQuery(GO_dbconn(), "select value from metadata where name='GOSOURCEDATE';")[,1]
fakedate <- gsub(" ", "_", format(as.POSIXct(fdate), "%a %b %d %H:%M:%S %Y"))


makeTable <- function(dbconn, fields, tableName) {
    sql <- paste0("create table if not exists ", tableName, " (date varchar(24) unique, ",
                  paste(paste(fields, "INTEGER"), collapse = ", "), ");")
    dbExecute(dbconn, sql)
}

insertTable <- function(dbconn, fields, tableName, vals, dateval) {
    sql <- paste0("insert into ", tableName, " (date, ", paste(fields, collapse = ", "),
                  ") values ('", dateval, "','", paste(vals, collapse = "', '"), "');")
    dbExecute(dbconn, sql)
}

## we can now just get the map_counts data from the installed db0 packages, and insert
## those values in the newly created map_counts.sqlite db.

getIt <- function(existingdb){
    require(existingdb, quietly = TRUE, character.only = TRUE)
    dbloc <- dir(paste0(path.package(existingdb), "/extdata"), "sqlite", full.names = TRUE)
    con <- dbConnect(SQLite(), dbloc[length(dbloc)])
    d.f <- dbGetQuery(con, "select * from map_counts;")
    dbDisconnect(con)
    d.f
}

mapcon <- dbConnect(SQLite(), "../../db/map_counts.sqlite")

for(i in seq(along = pkgnames)){
    mapdf <-  getIt(pkgnames[i])
    makeTable(mapcon, mapdf[,1], tablenames[i])
    insertTable(mapcon, mapdf[,1], tablenames[i], mapdf[,2], fakedate)
}

dbDisconnect(mapcon)

        
        
        
    
