#!/bin/sh
set -e
export UGSOURCEDATE_human=2013-Apr25
export UGSOURCEDATE_mouse=2013-Mar25
export UGSOURCEDATE_rat=2013-Apr15
export UGSOURCEDATE_fly=2013-Nov4
export UGSOURCEDATE_fish=2012-Jul9
export UGSOURCEDATE_canine=2013-Apr9
export UGSOURCEDATE_bovine=2012-Jul9
export UGSOURCEDATE_worm=2012-Nov5
export UGSOURCEDATE_pig=2012-Jul9
export UGSOURCEDATE_chicken=2012-Sep26
export UGSOURCEDATE_rhesus=2012-Sep10
export UGSOURCEDATE_xenopus=2013-Mar4
export UGSOURCEDATE_arabidopsis=2012-Jul9
export UGSOURCEDATE_anopheles=2013-Mar25
export UGSOURCENAME_human="UniGene (Homo sapiens)"
export UGSOURCENAME_mouse="UniGene (Mus musculus)"
export UGSOURCENAME_rat="UniGene (Rattus norvegicus)"
export UGSOURCENAME_fly="UniGene (Drosophila melanogaster)"
export UGSOURCENAME_fish="UniGene (Danio rerio)"
export UGSOURCENAME_canine="UniGene (Canis familiaris)"
export UGSOURCENAME_bovine="UniGene (Bos taurus)"
export UGSOURCENAME_worm="UniGene (Caenorhabditis elegans)"
export UGSOURCENAME_pig="UniGene (Sus scrofa)"
export UGSOURCENAME_chicken="UniGene (Gallus gallus)"
export UGSOURCENAME_rhesus="UniGene (Macaca mulatta)"
export UGSOURCENAME_xenopus="UniGene (Xenopus laevis)"
export UGSOURCENAME_arabidopsis="UniGene (Arabidopsis thaliana)"
export UGSOURCENAME_anopheles="UniGene (Anopheles gambiae)"
export UGSOURCEURL_human="ftp://ftp.ncbi.nih.gov/repository/UniGene/Homo_sapiens"
export UGSOURCEURL_mouse="ftp://ftp.ncbi.nih.gov/repository/UniGene/Mus_musculus"
export UGSOURCEURL_rat="ftp://ftp.ncbi.nih.gov/repository/UniGene/Rattus_norvegicus"
export UGSOURCEURL_fly="ftp://ftp.ncbi.nih.gov/repository/UniGene/Drosophila_melanogaster"
export UGSOURCEURL_fish="ftp://ftp.ncbi.nih.gov/repository/UniGene/Danio_rerio"
export UGSOURCEURL_canine="ftp://ftp.ncbi.nih.gov/repository/UniGene/Canis_lupus_familiaris"
export UGSOURCEURL_bovine="ftp://ftp.ncbi.nih.gov/repository/UniGene/Bos_taurus"
export UGSOURCEURL_worm="ftp://ftp.ncbi.nih.gov/repository/UniGene/Caenorhabditis_elegans"
export UGSOURCEURL_pig="ftp://ftp.ncbi.nih.gov/repository/UniGene/Sus_scrofa"
export UGSOURCEURL_chicken="ftp://ftp.ncbi.nih.gov/repository/UniGene/Gallus_gallus"
export UGSOURCEURL_rhesus="ftp://ftp.ncbi.nih.gov/repository/UniGene/Macaca_mulatta"
export UGSOURCEURL_xenopus="ftp://ftp.ncbi.nih.gov/repository/UniGene/Xenopus_laevis"
export UGSOURCEURL_arabidopsis="ftp://ftp.ncbi.nih.gov/repository/UniGene/Arabidopsis_thaliana"
export UGSOURCEURL_anopheles="ftp://ftp.ncbi.nih.gov/repository/UniGene/Anopheles_gambiae"
